### ISSUE TITLE
Circle highlighting current date not centered for non-monospace fonts

### ISSUE THREAD

**Issue by karlch** [chris-marsh/gcalendar#2]
Me again :smiley: 

Using a non-monospace font, the circle highlighting the current date looks slightly off for me. See the attached screenshot. Used font: Overpass 10.

![galendae_current](https://cloud.githubusercontent.com/assets/12006766/22863750/5d6de908-f146-11e6-91f3-94130dfa825e.png)

Suggestions for solving this:
a) Force the usage of a monospaced font.
b) Resize the calendar widget so it is a perfect multiple of columns and rows in pixel width/height.

I have a working patch for b). If you are interested, I can open a PR.

This is obviously quite nitpicking so feel free to close the issue if you think it isn't enough of a problem.

**Comment by chris-marsh** [comment]
Thanks again karlch, your input is very much appreciated. I don't think this issue is nitpicking at all, The off center highlight really does spoil the look.

I tried out the overpass font to reproduce the issue and can confirm. I had a play about and think you are spot on with the idea to resize based on exact mutiples. I believe the off centred circle is a decimal rounding issue when dividing to calculating the position.

I tried a fix by getting the remainder and halfing it to create an offset for the horizontal position. I doubt this method would be 100% accurate in all situations, but my initial tests seem to look okay. This is my ammended draw function;

    static gboolean draw_callback (GtkWidget *widget, cairo_t *cr, CalendarPtr this)
    {
        if (this->month == this->highlight_date.month &&
                this->year == this->highlight_date.year) {
            GdkRGBA color;
            gdk_rgba_parse(&color, this->highlight_color);
            gdk_cairo_set_source_rgba(cr, &color);
    
            int offset = (gtk_widget_get_allocated_width(GTK_WIDGET(widget)) % 7) / 2;
            int cell_width = gtk_widget_get_allocated_width(GTK_WIDGET(widget)) / 7;
            int cell_height = gtk_widget_get_allocated_height(GTK_WIDGET(widget)) / 6;
    
            cairo_arc(cr,
                    (this->highlight_cell.column*cell_width)-(cell_width / 2) + offset,
                    (this->highlight_cell.row*cell_height)-(cell_height / 2),
                    (cell_height / 2) - 1, 0, 2 * G_PI);
            cairo_stroke(cr);
        }
        return FALSE;       
    }

I'd be interested to see your patch to resize as it would have more accuracy.
